plugins {
	id 'application'
}

wrapper {
	gradleVersion = '9.5.1'
}

repositories {
	mavenCentral()
}

project.tasks.named("distZip") {
        duplicatesStrategy = 'exclude'
}

project.tasks.named("distTar") {
        duplicatesStrategy = 'exclude'
}

project.tasks.named("installDist") {
        duplicatesStrategy = 'exclude'
}

dependencies {
	implementation "com.cobber.fta:fta:18.+"
	implementation "de.siegmar:fastcsv:4.2.0"
	implementation "ch.qos.logback:logback-classic:1.5.32"
}

application {
	mainClass = 'cli.Cli'
}
